import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#9b9d9e",
        "on-primary-fixed-variant": "#435c85",
        "error": "#9f403d",
        "on-tertiary": "#fff8f1",
        "background": "#f8f9fa",
        "surface-tint": "#465f88",
        "secondary-dim": "#4d545d",
        "surface-bright": "#f8f9fa",
        "tertiary": "#785a1a",
        "on-tertiary-container": "#624604",
        "error-container": "#fe8983",
        "secondary": "#596069",
        "error-dim": "#4e0309",
        "primary-container": "#d6e3ff",
        "on-error-container": "#752121",
        "tertiary-fixed-dim": "#ecc479",
        "on-primary": "#f6f7ff",
        "secondary-fixed": "#dce3ee",
        "secondary-container": "#dce3ee",
        "tertiary-dim": "#6b4e0e",
        "on-secondary-fixed": "#394049",
        "on-tertiary-fixed": "#4a3400",
        "secondary-fixed-dim": "#ced5e0",
        "outline": "#737c7f",
        "primary-fixed-dim": "#c0d5ff",
        "surface-container-high": "#e3e9ec",
        "primary-dim": "#3a537b",
        "surface-variant": "#dbe4e7",
        "on-error": "#fff7f6",
        "on-secondary": "#f7f9ff",
        "on-primary-container": "#39527a",
        "tertiary-container": "#fbd185",
        "outline-variant": "#abb3b7",
        "on-secondary-container": "#4b525c",
        "surface-dim": "#d1dce0",
        "primary": "#465f88",
        "surface-container-low": "#f1f4f6",
        "on-primary-fixed": "#264067",
        "inverse-surface": "#0c0f10",
        "on-background": "#2b3437",
        "inverse-primary": "#aec7f6",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-fixed-variant": "#6c500f",
        "surface-container": "#eaeff1",
        "surface": "#f8f9fa",
        "on-secondary-fixed-variant": "#555c66",
        "surface-container-highest": "#dbe4e7",
        "tertiary-fixed": "#fbd185",
        "on-surface": "#2b3437",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#586064",
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
